### ISSUE TITLE
args[0].resourcePath无法获取到

### ISSUE THREAD

**Issue by regboy8** [yinchengnuo/templateWxappUniapp#1]
你好，按你的方式操作，编译时出错，以下是相关的代码
`
module.exports = {
	chainWebpack: config => {
		config.module.rule('vue').use('vue-loader').loader('vue-loader').tap(options => {
			const compile = options.compiler.compile
			options.compiler.compile = (template, ...args) => {
				if (args[0].resourcePath.match(/^pages/)) {
					template = template.replace(/[\s\S]+?<[\d\D]+?>/, _ => `${_}
						<custom-interactive ref="custom-interactive" style="position: fixed; z-index: 123;" />
					`)
				}
				return compile(template, ...args)
			}
			return options
		})
	}
}

`
我调试了一下，出错的原因是“args[0].resourcePath”这个参数不存在。args打印出来是：
`
14:55:39.503 [ { outputSourceRange: true,
14:55:39.509     preserveWhitespace: false,
14:55:39.515     h5: true,
14:55:39.525     modules: [ [Object], [Object], [Object], [Object] ],
14:55:39.531     filterModules: [],
14:55:39.532     scopeId: 'data-v-4e43f4e2',
14:55:39.540     comments: undefined } ]
`

**Comment by yinchengnuo** [comment]
可能是 h5 不支持，目前貌似只有小程序支持发自我的华为手机-------- 原始邮件 --------发件人： regboy8 <notifications@github.com>日期： 2020年8月25日周二 14:57收件人： yinchengnuo/templateWxappUniapp <templateWxappUniapp@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [yinchengnuo/templateWxappUniapp] args[0].resourcePath无法获取到 (#1)

你好，按你的方式操作，编译时出错，以下是相关的代码

module.exports = { chainWebpack: config => { config.module.rule('vue').use('vue-loader').loader('vue-loader').tap(options => { const compile = options.compiler.compile options.compiler.compile = (template, ...args) => { if (args[0].resourcePath.match(/^pages/)) { template = template.replace(/[\s\S]+?<[\d\D]+?>/, _ =>${_}



`)

}

return compile(template, ...args)

}

return options

})

}

}

我调试了一下，出错的原因是“args[0].resourcePath”这个参数不存在。args打印出来是：

14:55:39.503 [ { outputSourceRange: true,

14:55:39.509     preserveWhitespace: false,

14:55:39.515     h5: true,

14:55:39.525     modules: [ [Object], [Object], [Object], [Object] ],

14:55:39.531     filterModules: [],

14:55:39.532     scopeId: 'data-v-4e43f4e2',

14:55:39.540     comments: undefined } ]

`

**Comment by regboy8** [comment]
我这边是用uniapp做app、h5、小程序的，也是想不手动在每个页面上插入一些公共的插件，不知道有没其他的方法可以做到，不然一个个页面加也是够累的
